package com.thyids.ai_girl_friend.entities.client.renderer;

import com.mojang.blaze3d.vertex.PoseStack;
import com.thyids.ai_girl_friend.Ai_girl_friend;
import com.thyids.ai_girl_friend.entities.client.model.CreeperMotherModel;
import com.thyids.ai_girl_friend.world.entity.girl_friend.CreeperMother;
import net.minecraft.client.renderer.MultiBufferSource;
import net.minecraft.client.renderer.entity.EntityRendererProvider;
import net.minecraft.client.renderer.entity.MobRenderer;
import net.minecraft.resources.ResourceLocation;

public class CreeperMotherRenderer extends MobRenderer<CreeperMother, CreeperMotherModel<CreeperMother>> {
    public CreeperMotherRenderer(EntityRendererProvider.Context pContext) {
        super(pContext, new CreeperMotherModel<CreeperMother>(
                pContext.bakeLayer(CreeperMotherModel.CREEPER_MOTHER_LAYER)
        ), 0.5F);
    }

    @Override
    public ResourceLocation getTextureLocation(CreeperMother pEntity) {
        return switch (pEntity.getVariant()) {
            // 已存在 + 补全所有图片，共 210 个皮肤
            case 1 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/jk.png");
            case 2 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/cute.png");
            case 3 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/maid.png");
            case 4 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/creeper_mother.png");
            case 5 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/nova.png");
            case 6 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/sunny.png");
            case 7 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/willow.png");
            case 8 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/chloe.png");
            case 9 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/lily.png");
            case 10 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/coco.png");
            case 11 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/luna.png");
            case 12 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/roxy.png");
            case 13 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/lira.png");
            case 14 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/mera.png");
            case 15 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/sora.png");
            case 16 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/elva.png");
            case 17 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/nyla.png");
            case 18 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/kira.png");
            case 19 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/zora.png");
            case 20 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/thea.png");
            case 21 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/irys.png");
            case 22 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/lila.png");
            case 23 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/faye.png");
            case 24 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/skye.png");
            case 25 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/rina.png");
            case 26 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/maya.png");
            case 27 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/lunad.png");
            case 28 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/aria.png");
            case 29 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/bela.png");
            case 30 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/cora.png");
            case 31 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/dila.png");
            case 32 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/eira.png");
            case 33 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/fira.png");
            case 34 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/gigi.png");
            case 35 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/hana.png");
            case 36 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/isla.png");
            case 37 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/joli.png");
            case 38 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/kyla.png");
            case 39 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/mila.png");
            case 40 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/nika.png");
            case 41 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/ona.png");
            case 42 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/pippa.png");
            case 43 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/qara.png");
            case 44 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/ria.png");
            case 45 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/sia.png");
            case 46 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/tala.png");
            case 47 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/una.png");
            case 48 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/vivi.png");
            case 49 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/wila.png");
            case 50 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/xyla.png");
            case 51 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/yara.png");
            case 52 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/zara.png");
            case 53 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/ayla.png");
            case 54 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/bella.png");
            case 55 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/clara.png");
            case 56 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/dina.png");
            case 57 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/ella.png");
            case 58 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/gia.png");
            case 59 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/hera.png");
            case 60 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/iris.png");
            case 61 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/jane.png");
            case 62 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/kiki.png");
            case 63 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/lala.png");
            case 64 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/mena.png");
            case 65 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/nola.png");
            case 66 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/ola.png");
            case 67 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/pola.png");
            case 68 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/rola.png");
            case 69 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/suki.png");
            case 70 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/tira.png");
            case 71 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/ula.png");
            case 72 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/vara.png");
            case 73 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/wini.png");
            case 74 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/xara.png");
            case 75 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/yuli.png");
            case 76 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/zuri.png");
            case 77 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/aisha.png");
            case 78 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/bria.png");
            case 79 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/cici.png");
            case 80 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/dara.png");
            case 81 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/ema.png");
            case 82 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/fara.png");
            case 83 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/hila.png");
            case 84 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/iva.png");
            case 85 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/jara.png");
            case 86 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/kala.png");
            case 87 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/miki.png");
            case 88 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/bade.png");
            case 89 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/codea.png");
            case 90 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/mamad.png");
            case 91 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/fews.png");
            // ===================== 以下为补全的全部缺失皮肤 =====================
            case 92 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/adis.png");
            case 93 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/adra.png");
            case 94 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/anna.png");
            case 95 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/arni.png");
            case 96 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/beri.png");
            case 97 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/bixy.png");
            case 98 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/bona.png");
            case 99 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/bree.png");
            case 100 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/bris.png");
            case 101 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/bryn.png");
            case 102 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/cala.png");
            case 103 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/cana.png");
            case 104 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/cary.png");
            case 105 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/cino.png");
            case 106 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/cozy.png");
            case 107 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/dana.png");
            case 108 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/dazy.png");
            case 109 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/dema.png");
            case 110 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/demi.png");
            case 111 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/dona.png");
            case 112 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/dori.png");
            case 113 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/elka.png");
            case 114 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/elmy.png");
            case 115 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/elna.png");
            case 116 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/elri.png");
            case 117 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/elsie.png");
            case 118 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/elyn.png");
            case 119 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/envy.png");
            case 120 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/fana.png");
            case 121 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/fari.png");
            case 122 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/fina.png");
            case 123 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/fray.png");
            case 124 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/gala.png");
            case 125 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/gana.png");
            case 126 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/geli.png");
            case 127 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/gisa.png");
            case 128 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/gona.png");
            case 129 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/hali.png");
            case 130 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/hani.png");
            case 131 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/hela.png");
            case 132 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/hory.png");
            case 133 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/iana.png");
            case 134 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/indy.png");
            case 135 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/inka.png");
            case 136 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/inos.png");
            case 137 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/ivy.png");
            case 138 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/jali.png");
            case 139 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/jana.png");
            case 140 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/jani.png");
            case 141 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/jola.png");
            case 142 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/jory.png");
            case 143 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/kali.png");
            case 144 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/kana.png");
            case 145 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/kery.png");
            case 146 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/kina.png");
            case 147 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/kora.png");
            case 148 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/lana.png");
            case 149 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/lark.png");
            case 150 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/leva.png");
            case 151 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/lina.png");
            case 152 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/loma.png");
            case 153 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/loni.png");
            case 154 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/lyra.png");
            case 155 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/maeve.png");
            case 156 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/maia.png");
            case 157 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/mari.png");
            case 158 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/mika.png");
            case 159 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/mina.png");
            case 160 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/mira.png");
            case 161 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/mona.png");
            case 162 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/nana.png");
            case 163 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/naya.png");
            case 164 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/nela.png");
            case 165 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/nera.png");
            case 166 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/neve.png");
            case 167 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/nix.png");
            case 168 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/nori.png");
            case 169 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/okra.png");
            case 170 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/olia.png");
            case 171 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/olie.png");
            case 172 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/olyn.png");
            case 173 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/onni.png");
            case 174 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/opal.png");
            case 175 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/pani.png");
            case 176 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/pari.png");
            case 177 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/pela.png");
            case 178 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/pixy.png");
            case 179 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/qani.png");
            case 180 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/rani.png");
            case 181 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/rasi.png");
            case 182 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/ravi.png");
            case 183 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/rhia.png");
            case 184 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/sage.png");
            case 185 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/saka.png");
            case 186 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/sari.png");
            case 187 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/sena.png");
            case 188 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/sola.png");
            case 189 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/tali.png");
            case 190 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/tess.png");
            case 191 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/tina.png");
            case 192 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/tova.png");
            case 193 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/tris.png");
            case 194 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/ulie.png");
            case 195 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/ulna.png");
            case 196 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/unna.png");
            case 197 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/uray.png");
            case 198 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/vale.png");
            case 199 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/vani.png");
            case 200 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/vega.png");
            case 201 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/veta.png");
            case 202 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/vira.png");
            case 203 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/wari.png");
            case 204 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/wena.png");
            case 205 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/wisp.png");
            case 206 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/wren.png");
            case 207 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/wyla.png");
            case 208 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/xani.png");
            case 209 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/xena.png");
            case 210 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/xila.png");
            case 211 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/yana.png");
            case 212 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/yuka.png");
            case 213 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/yori.png");
            case 214 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/zana.png");
            case 215 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/zari.png");
            case 216 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/zeli.png");
            case 217 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/ziva.png");
            case 218 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/zoha.png");
            case 219 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/zory.png");
            case 220 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/wira.png");
            case 221 -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/mana.png");
            // 默认兜底
            default -> new ResourceLocation(Ai_girl_friend.MOD_ID, "textures/entity/woman/not.png");
        };
    }
}
